import '../models.dart';
import 'tenant_config.dart';

/// Minimal defaults for new / non-NSK tenants (no Novosibirsk content).
TenantConfig blankTenantConfig(String tenantId) => TenantConfig(
      tenantId: tenantId,
      communityName: {'he': '', 'en': '', 'ru': ''},
      cityName: {'he': '', 'en': '', 'ru': ''},
      tagline: {'he': '', 'en': '', 'ru': ''},
      homeStats: const [],
      aboutSubtitle: {'he': '', 'en': '', 'ru': ''},
      aboutBody: {'he': '', 'en': '', 'ru': ''},
      address: {'he': '', 'en': '', 'ru': ''},
      phone: '',
      email: '',
      hours: const [],
      staff: const [],
      social: TenantSocialLinks(
        telegram: '',
        vk: '',
        youtube: '',
        facebook: '',
        instagram: '',
        website: '',
        donateUrl: '',
        bankDetails: '',
      ),
      whatsAppDigits: '',
      defaultAdminEmails: '',
      defaultPaletteId: 'classic',
      emblemAssetPath: '',
      locationQuery: '',
      latitude: 0,
      longitude: 0,
      timezone: 'UTC',
      kaddishHost: 'https://kaddish.example.invalid',
      kaddishServiceId: 'demo',
      seoTitle: 'Chabad community',
      enabledLanguages: const ['ru', 'he', 'en'],
      defaultLanguage: 'ru',
      telegramChannelHint: '',
      landlineDigits: '',
      primaryColorHex: null,
      accentColorHex: null,
      sourceCredit: '',
    );
